; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
; Lower upload speed often fixes stk500v2_ReceiveMessage(): timeout on Mega
upload_speed = 115200
; Local lib: lib/Dimmable Light for Arduino. ArduinoSTL required by that lib (manager).
lib_deps = 
    mike-matera/ArduinoSTL@^1.1.0
    ingelobito/RBDdimmer@^1.0